### ISSUE TITLE
Implement Explicit Aspects

### ISSUE THREAD

**Issue by WalterWoshid** [okapi-web/php-aop#8]
- **Implicit:** The aspects are applied without any modification to the
  target classes. The aspect itself specifies the classes or methods it applies
  to.
- **Class-Level Explicit:** The aspects are applied by modifying the
  target classes, typically by adding the aspect as an attribute to the target
  class.
- **Method-Level Explicit:** The aspects are applied by modifying the
  target classes, typically by adding the aspect as an attribute to the target
  method.

**Explicit Aspects don't need to be registered, only the AopKernel needs to be registered and they will be automatically detected.**

## Example Method-Level Explicit

```php
// Target class
class PaymentProcessor
{
    #[Payment]
    public function processPayment($amount): void
    {
        // process payment logic
    }
}

// Aspect
#[Attribute]
#[Aspect]
class PaymentProcessorAspect
{
    #[Before]
    public function checkPaymentAmount(BeforeMethodInvocation $invocation): void
    {
        $payment = $invocation->getArgument('amount');
        
        if ($payment < 0) {
            throw new InvalidArgumentException('Invalid payment amount');
        }
    }
}
```

## Example Class-Level Explicit

```php
// Target class
#[Payment]
class PaymentProcessor
{
    public function processPayment($amount): void
    {
        // process payment logic
    }
}

// Aspect
#[Attribute]
#[Aspect]
class PaymentProcessorAspect
{
    // Match all methods
    #[Before]
    // or match a specific method
    #[Before(
        method: 'processPayment',
    )]
    public function checkPaymentAmount(BeforeMethodInvocation $invocation): void
    {
        $payment = $invocation->getArgument('amount');
        
        if ($payment < 0) {
            throw new InvalidArgumentException('Invalid payment amount');
        }
    }
}
```

# TODO
- [x] Create Test Cases
  - [x] Test for explicit method-level aspects
  - [x] Test for explicit class-level aspects
  - [x] Test for using `#[Before]`, `#[Around]` and `#[After]` not directly and without `class` or `method`
  - [x] Kernel with explicit aspects only
  - [x] Same explicit aspect for different target classes
- [x] Implement
  - [x] Using explicit method-level aspects
  - [x] Using explicit class-level aspects
  - [x] Throw an error for not using `class` or `method` if not a direct aspect
- [x] Document in README.md

**Comment by WalterWoshid** [comment]
Done: https://github.com/okapi-web/php-aop/pull/20
